#ifndef __DV_CERT_H__
#define __DV_CERT_H__

typedef enum _DV_CERT_SIGN_ALGORITHM_E {
    DV_CERT_RSA_SIGN = 1,
    DV_CERT_DSS_SIGN = 2,
    DV_CERT_ECDSA_SIGN = 64,
} DV_CERT_SIGN_ALGORITHM_E;

#define DV_CERT_SIGN_ALGORITHM_RSA_SIGN     0x01
#define DV_CERT_SIGN_ALGORITHM_DSA_SIGN     0x02
#define DV_CERT_SIGN_ALGORITHM_ECDSA_SIGN   0x03

#define DV_CERT_HASH_ALGORITHM_SHA512       0x06
#define DV_CERT_HASH_ALGORITHM_SHA384       0x05
#define DV_CERT_HASH_ALGORITHM_SHA256       0x04

#endif
